"use client";

import React from 'react';
import Link from 'next/link';

const TermsOfServicePage = () => {
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-gradient-to-r from-purple-600 to-pink-600 text-white py-12">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <Link href="/" className="inline-flex items-center text-white hover:text-purple-200 transition-colors mb-6 group">
            <svg className="h-5 w-5 mr-2 transform group-hover:-translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
            Back to Home
          </Link>
          <h1 className="text-4xl sm:text-5xl font-bold mb-4">Terms and Conditions</h1>
          <p className="text-lg text-purple-100">Last Updated: {new Date().toLocaleDateString()}</p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-8 lg:p-12">
          <div className="prose prose-lg max-w-none prose-headings:text-gray-900 prose-headings:font-semibold prose-h2:text-2xl prose-h2:mt-8 prose-h2:mb-4 prose-h3:text-xl prose-h3:mt-6 prose-h3:mb-3 prose-p:text-gray-700 prose-p:leading-relaxed prose-li:text-gray-700 prose-strong:text-gray-900 prose-a:text-purple-600 prose-a:no-underline hover:prose-a:text-purple-800 hover:prose-a:underline">
          <h2>1. Introduction and Acceptance</h2>
          <p>
            By accessing or using Garnet AI's website, products, or services (collectively, the "Service"), you agree to be bound by these Terms and Conditions ("Terms"). If you do not agree with any part of these Terms, you must not use the Service. These Terms constitute a legally binding agreement between you (individually or on behalf of your company) and Garnet AI Limited, a company incorporated and registered in Ireland with its registered office at [Address], ("Garnet AI," "we," "us," or "our").
          </p>

          <h2>2. Definitions</h2>
          <ul>
            <li><strong>"User," "you," or "your"</strong> means any individual or entity accessing or using the Service.</li>
            <li><strong>"Content"</strong> refers to any text, data, information, graphics, code, or other materials provided by you to the Service or generated by the Service on your behalf.</li>
            <li><strong>"Subscription Plan"</strong> refers to any paid or free plan that grants access to certain features of the Service.</li>
          </ul>

          <h2>3. Eligibility and Account Registration</h2>
          <p>
            You must be at least 18 years old to use the Service. By registering for an account, you represent and warrant that you have the legal capacity to enter into these Terms and that all information you provide is accurate and complete. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account or any other breach of security.
          </p>

          <h2>4. Use of the Service</h2>
          <h3>4.1. License Grant</h3>
          <p>
            Subject to these Terms and your compliance herewith, Garnet AI grants you a non-exclusive, non-transferable, revocable license to use the Service solely for your internal business purposes.
          </p>
          
          <h3>4.2. User Conduct</h3>
          <p>You agree not to:</p>
          <ul>
            <li>Use the Service for any unlawful purpose or in violation of applicable laws or regulations.</li>
            <li>Reverse engineer, decompile, or disassemble any portion of the Service.</li>
            <li>Impersonate any person or entity or falsely state or misrepresent your affiliation with any person or entity.</li>
            <li>Upload or transmit any malicious code, spam, or any material that infringes third-party intellectual property rights.</li>
          </ul>

          <h2>5. Intellectual Property Rights</h2>
          <p>
            All intellectual property rights, including but not limited to copyrights, trademarks, trade secrets, patents, and other proprietary rights in and to the Service (including the software, content, user interface, and related documentation) are owned by Garnet AI or its licensors. You acknowledge and agree that except for the limited license expressly granted herein, no ownership or rights in the Service are transferred to you and that all goodwill associated therewith inures to Garnet AI's benefit.
          </p>

          <h2>9. Disclaimers and Warranties</h2>
          <h3>9.1. "As-Is" Service</h3>
          <p>
            <strong>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE," AND GARNET AI DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.</strong>
          </p>
          
          <h3>9.2. No Warranty of Uninterrupted Service</h3>
          <p>
            <strong>GARNET AI DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE.</strong>
          </p>
          
          <h3>9.3. Accuracy of Results</h3>
          <p>
            <strong>THE SERVICE UTILIZES ARTIFICIAL INTELLIGENCE MODELS AND THIRD-PARTY DATA SOURCES, AND THE RESULTS PROVIDED MAY NOT BE ACCURATE OR COMPLETE. GARNET AI MAKES NO REPRESENTATION OR WARRANTY REGARDING THE ACCURACY OR RELIABILITY OF ANY CONTENT OR DATA GENERATED OR ANALYZED BY THE SERVICE.</strong>
          </p>

          <h2>10. Limitation of Liability</h2>
          <p>
            <strong>TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL GARNET AI, ITS AFFILIATES, LICENSORS, OR SERVICE PROVIDERS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES RESULTING FROM (A) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE; (B) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICE; (C) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT; OR (D) ANY OTHER MATTER RELATING TO THE SERVICE, INCLUDING BUT NOT LIMITED TO ERRORS OR OMISSIONS IN THE SERVICE.</strong>
          </p>
          <p>
            <strong>IN NO EVENT WILL GARNET AI'S AGGREGATE LIABILITY ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR YOUR USE OF THE SERVICE EXCEED THE TOTAL AMOUNT OF FEES PAID BY YOU TO GARNET AI IN THE SIX (6) MONTHS PRECEDING THE CLAIM. THE FOREGOING LIMITATIONS WILL APPLY EVEN IF GARNET AI HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND REGARDLESS OF THE THEORY OF LIABILITY.</strong>
          </p>

          <h2>12. Governing Law and Dispute Resolution</h2>
          <p>
            These Terms and any dispute arising out of or relating to these Terms or the Service will be governed by and construed in accordance with the laws of Ireland, without regard to conflict of law principles. Any dispute or claim arising out of or relating to these Terms or the Service will be resolved exclusively before the courts located in Dublin, Ireland, and you consent to the personal jurisdiction and venue of such courts.
          </p>

          <h2>13. Modifications to Terms</h2>
          <p>
            Garnet AI may modify these Terms from time to time. If material changes are made, Garnet AI will provide notice by posting the revised Terms and updating the "Last Updated" date at the top of these Terms. Your continued use of the Service after such modifications constitutes your acceptance of the revised Terms.
          </p>

          <h2>14. Severability</h2>
          <p>
            If any provision of these Terms is held to be invalid or unenforceable by a court of competent jurisdiction, that provision will be struck and the remaining provisions will remain in full force and effect.
          </p>

          <h2>15. Entire Agreement</h2>
          <p>
            These Terms, together with any Order Form(s), constitute the entire agreement between you and Garnet AI regarding the Service and supersede all prior and contemporaneous agreements, proposals, or representations, written or oral, concerning the Service.
          </p>
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className="bg-gray-50 border-t border-gray-200 py-8">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <p className="text-gray-600">
            © {new Date().getFullYear()} Garnet AI Limited. All rights reserved.
          </p>
          <div className="mt-4 space-x-6">
            <Link href="/privacy-policy" className="text-purple-600 hover:text-purple-800">
              Privacy Policy
            </Link>
            <Link href="/terms-of-service" className="text-purple-600 hover:text-purple-800">
              Terms and Conditions
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsOfServicePage; 
