[build]
  # Build command for the frontend Next.js app with static export
  command = "cd frontend && npm run build:netlify"
  
  # Directory to publish (Next.js static export automatically outputs to 'out')
  publish = "frontend/out"
  
  # Functions directory
  functions = "frontend/.netlify/functions"
  
  # Environment variables
  [build.environment]
    NODE_VERSION = "18"
    NEXT_PUBLIC_API_URL = "https://garnet-compliance-saas-production.up.railway.app"

# Disable Netlify's automatic optimizations that interfere with React hydration
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

# Headers to prevent caching issues
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# CRITICAL: Ensure JS and CSS files are served with correct MIME types BEFORE any redirects
[[headers]]
  for = "/_next/static/chunks/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/js/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/css/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[context.production]
  command = "cd frontend && npm run build:netlify"
  publish = "frontend/out"

[context.deploy-preview]
  command = "cd frontend && npm run build:netlify"
  publish = "frontend/out"

[context.branch-deploy]
  command = "cd frontend && npm run build:netlify"
  publish = "frontend/out"

# IMPORTANT: Static assets must be handled BEFORE SPA redirects
# Redirects for API routes to backend
[[redirects]]
  from = "/api/*"
  to = "https://garnet-compliance-saas-production.up.railway.app/api/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/ask"
  to = "https://garnet-compliance-saas-production.up.railway.app/ask"
  status = 200

[[redirects]]
  from = "/status"
  to = "https://garnet-compliance-saas-production.up.railway.app/status"
  status = 200

[[redirects]]
  from = "/health"
  to = "https://garnet-compliance-saas-production.up.railway.app/health"
  status = 200

[[redirects]]
  from = "/ping"
  to = "https://garnet-compliance-saas-production.up.railway.app/ping"
  status = 200

# SPA routing redirects - ONLY for HTML pages, NOT static assets
[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["request"], "force" = false}

[[redirects]]
  from = "/auth/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["request"], "force" = false}

[[redirects]]
  from = "/questionnaires/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["request"], "force" = false}

[[redirects]]
  from = "/vendors/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["request"], "force" = false}

[[redirects]]
  from = "/trust-portal/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["request"], "force" = false}

[[redirects]]
  from = "/compliance/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["request"], "force" = false}

[[redirects]]
  from = "/contact/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["request"], "force" = false}

# Catch-all for SPA - ONLY for non-asset requests
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["request"], "force" = false} 