[build]
  # Build command for the frontend Next.js app with static export
  command = "cd frontend && npm install && npm run build"
  
  # Directory to publish (Next.js static export automatically outputs to 'out')
  publish = "frontend/out"
  
  # Functions directory
  functions = "frontend/.netlify/functions"
  
  # Environment variables
  [build.environment]
    NODE_VERSION = "18"
    NEXT_PUBLIC_API_URL = "https://garnet-compliance-saas-production.up.railway.app"

# Disable Netlify's automatic optimizations that interfere with React hydration
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

# Headers to prevent caching issues
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Disable Pretty URLs and optimize for React
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[context.production]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/out"

[context.deploy-preview]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/out"

[context.branch-deploy]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/out"

# Redirects for API routes to Netlify functions
[[redirects]]
  from = "/api/vendors"
  to = "/.netlify/functions/vendors"
  status = 200

[[redirects]]
  from = "/api/vendors/stats"
  to = "/.netlify/functions/vendor-stats"
  status = 200

[[redirects]]
  from = "/api/vendors/:id"
  to = "/.netlify/functions/vendor-by-id?id=:id"
  status = 200

# Redirects for SPA routing (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 