[build]
  # Build command for the frontend Next.js app (no static export)
  command = "cd frontend && npm install && npm run build"
  
  # Directory to publish - standard Next.js build output for Netlify
  publish = "frontend"
  
  # Functions directory
  functions = "frontend/.netlify/functions"
  
  # Environment variables
  [build.environment]
    NODE_VERSION = "18"
    NEXT_PUBLIC_API_URL = "https://garnet-compliance-saas-production.up.railway.app"

# Enable Next.js runtime for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers to prevent caching issues
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache optimization for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for API routes to Netlify functions
[[redirects]]
  from = "/api/vendors"
  to = "/.netlify/functions/vendors"
  status = 200

[[redirects]]
  from = "/api/vendors/stats"
  to = "/.netlify/functions/vendor-stats"
  status = 200

[[redirects]]
  from = "/api/vendors/:id"
  to = "/.netlify/functions/vendor-by-id?id=:id"
  status = 200

# Catch-all redirect for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 