[build]
  # Set base directory to frontend folder
  base = "frontend"
  
  # Build command for Next.js static export
  command = "npm install && npm run build"
  
  # Directory to publish - static export output directory
  publish = "out"
  
  # Functions directory (optional for static export)
  functions = ".netlify/functions"
  
  # Environment variables
  [build.environment]
    NODE_VERSION = "18"
    NEXT_PUBLIC_API_URL = "https://garnet-compliance-saas-production.up.railway.app"
    # Skip the Next.js plugin since we're using static export
    NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Disable Next.js runtime plugin for static export
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache optimization for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for API routes to external backend (Railway)
[[redirects]]
  from = "/api/vendors"
  to = "https://garnet-compliance-saas-production.up.railway.app/api/vendors"
  status = 200

[[redirects]]
  from = "/api/vendors/stats"
  to = "https://garnet-compliance-saas-production.up.railway.app/api/vendors/stats"
  status = 200

[[redirects]]
  from = "/api/vendors/:id"
  to = "https://garnet-compliance-saas-production.up.railway.app/api/vendors/:id"
  status = 200

# Catch-all redirect for all other API routes
[[redirects]]
  from = "/api/*"
  to = "https://garnet-compliance-saas-production.up.railway.app/api/:splat"
  status = 200

# Catch-all redirect for client-side routing (SPA mode)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 